# Generated by Django 2.2.6 on 2019-11-19 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_order_billing_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='saler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saler', to='shop.Farmer'),
        ),
    ]
