# Generated by Django 2.2.6 on 2019-11-20 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_item_saler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Cows', 'Cows'), ('Chicken', 'Chicken'), ('Goats', 'Goats'), ('Ducks', 'Ducks'), ('Sheep', 'Sheep'), ('Rabits', 'Rabits'), ('Pigs', 'Pigs')], max_length=10),
        ),
    ]
