# Generated by Django 2.2.6 on 2019-11-26 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20191126_0341'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='saler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Farmer'),
        ),
    ]
