# Generated by Django 2.2.6 on 2019-11-26 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_auto_20191126_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem2',
            name='saler',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
