# Generated by Django 2.2.6 on 2019-11-26 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_auto_20191126_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='orderitem2',
            name='saler1',
        ),
        migrations.AddField(
            model_name='orderitem2',
            name='saler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Farmer'),
        ),
    ]
