# Generated by Django 2.2.6 on 2019-11-27 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_auto_20191126_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem2',
            name='saler',
        ),
    ]
